@set allusersprofile=c:\programdata
@set amdappsdkroot=c:\program files (x86)\amd app\
@set android_sdk=c:\users\user\appdata\local\android\sdk
@set appdata=c:\users\user\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=acer
@set comspec=c:\windows\system32\cmd.exe
@set dnx_home=%userprofile%\.dnx
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64
@set frameworkdir64=c:\windows\microsoft.net\framework64
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\user
@set include=c:\program files (x86)\microsoft visual studio 14.0\vc\include;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\8.1\include\\shared;c:\program files (x86)\windows kits\8.1\include\\um;c:\program files (x86)\windows kits\8.1\include\\winrt
@set java_home=c:\program files\java\jdk1.8.0_91
@set lib=c:\program files (x86)\microsoft visual studio 14.0\vc\lib\amd64;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib\amd64;c:\program files (x86)\windows kits\10\lib\10.0.10240.0\ucrt\x64;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x64
@set libpath=c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\lib\amd64;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib\amd64;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\user\appdata\local
@set logonserver=\\acer
@set msbuildloadmicrosofttargetsreadonly=true
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin\amd64;c:\program files (x86)\microsoft visual studio 14.0\vc\bin\amd64;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\microsoft visual studio 14.0\common7\ide;c:\program files (x86)\microsoft visual studio 14.0\common7\tools;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x64;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\program files\haskell\bin;c:\program files\haskell platform\8.0.2\lib\extralibs\bin;c:\program files\haskell platform\8.0.2\bin;c:\programdata\oracle\java\javapath;c:\program files (x86)\amd app\bin\x86_64;c:\program files (x86)\amd app\bin\x86;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\intel\opencl sdk\3.0\bin\x86;c:\program files (x86)\intel\opencl sdk\3.0\bin\x64;c:\program files\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files (x86)\ati technologies\ati.ace\core-static;c:\program files\git\cmd;c:\program files\microsoft\web platform installer\;c:\windows\system32\config\systemprofile\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files (x86)\skype\phone\;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\common files\acronis\snapapi\;c:\gnuwin32\bin;c:\gnuwin32\bin;c:\program files\cmake\bin;c:\program files\tortoisegit\bin;c:\program files\haskell platform\8.0.2\mingw\bin;c:\users\user\appdata\roaming\cabal\bin;c:\users\user\appdata\roaming\local\bin;c:\users\user\.dnx\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\user\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 69 stepping 1, genuineintel
@set processor_level=6
@set processor_revision=4501
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set sdk_2016=c:\sdk_2016
@set sessionname=console
@set stack_root=c:\sr
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\user\appdata\local\temp
@set tmp=c:\users\user\appdata\local\temp
@set ucrtversion=10.0.10240.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=acer
@set userdomain_roamingprofile=acer
@set username=user
@set userprofile=c:\users\user
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 14.0\vc\
@set visualstudiodir=c:\users\user\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio professional 2015
@set visualstudioversion=14.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 14.0\
@set vslang=1049
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdklibversion=winv6.3\
@set windowssdkversion=\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\

@call cl.exe